# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rafael/driver-ga

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rafael/driver-ga

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rafael/driver-ga/CMakeFiles /home/rafael/driver-ga/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rafael/driver-ga/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DriverGeneticAlgorithm

# Build rule for target.
DriverGeneticAlgorithm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DriverGeneticAlgorithm
.PHONY : DriverGeneticAlgorithm

# fast build rule for target.
DriverGeneticAlgorithm/fast:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/build
.PHONY : DriverGeneticAlgorithm/fast

Genetic_Algorithm/Chromosome.o: Genetic_Algorithm/Chromosome.cpp.o

.PHONY : Genetic_Algorithm/Chromosome.o

# target to build an object file
Genetic_Algorithm/Chromosome.cpp.o:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/Genetic_Algorithm/Chromosome.cpp.o
.PHONY : Genetic_Algorithm/Chromosome.cpp.o

Genetic_Algorithm/Chromosome.i: Genetic_Algorithm/Chromosome.cpp.i

.PHONY : Genetic_Algorithm/Chromosome.i

# target to preprocess a source file
Genetic_Algorithm/Chromosome.cpp.i:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/Genetic_Algorithm/Chromosome.cpp.i
.PHONY : Genetic_Algorithm/Chromosome.cpp.i

Genetic_Algorithm/Chromosome.s: Genetic_Algorithm/Chromosome.cpp.s

.PHONY : Genetic_Algorithm/Chromosome.s

# target to generate assembly for a file
Genetic_Algorithm/Chromosome.cpp.s:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/Genetic_Algorithm/Chromosome.cpp.s
.PHONY : Genetic_Algorithm/Chromosome.cpp.s

Genetic_Algorithm/DriverGeneticAlgorithm.o: Genetic_Algorithm/DriverGeneticAlgorithm.cpp.o

.PHONY : Genetic_Algorithm/DriverGeneticAlgorithm.o

# target to build an object file
Genetic_Algorithm/DriverGeneticAlgorithm.cpp.o:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/Genetic_Algorithm/DriverGeneticAlgorithm.cpp.o
.PHONY : Genetic_Algorithm/DriverGeneticAlgorithm.cpp.o

Genetic_Algorithm/DriverGeneticAlgorithm.i: Genetic_Algorithm/DriverGeneticAlgorithm.cpp.i

.PHONY : Genetic_Algorithm/DriverGeneticAlgorithm.i

# target to preprocess a source file
Genetic_Algorithm/DriverGeneticAlgorithm.cpp.i:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/Genetic_Algorithm/DriverGeneticAlgorithm.cpp.i
.PHONY : Genetic_Algorithm/DriverGeneticAlgorithm.cpp.i

Genetic_Algorithm/DriverGeneticAlgorithm.s: Genetic_Algorithm/DriverGeneticAlgorithm.cpp.s

.PHONY : Genetic_Algorithm/DriverGeneticAlgorithm.s

# target to generate assembly for a file
Genetic_Algorithm/DriverGeneticAlgorithm.cpp.s:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/Genetic_Algorithm/DriverGeneticAlgorithm.cpp.s
.PHONY : Genetic_Algorithm/DriverGeneticAlgorithm.cpp.s

Genetic_Algorithm/GaAdapter.o: Genetic_Algorithm/GaAdapter.cpp.o

.PHONY : Genetic_Algorithm/GaAdapter.o

# target to build an object file
Genetic_Algorithm/GaAdapter.cpp.o:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/Genetic_Algorithm/GaAdapter.cpp.o
.PHONY : Genetic_Algorithm/GaAdapter.cpp.o

Genetic_Algorithm/GaAdapter.i: Genetic_Algorithm/GaAdapter.cpp.i

.PHONY : Genetic_Algorithm/GaAdapter.i

# target to preprocess a source file
Genetic_Algorithm/GaAdapter.cpp.i:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/Genetic_Algorithm/GaAdapter.cpp.i
.PHONY : Genetic_Algorithm/GaAdapter.cpp.i

Genetic_Algorithm/GaAdapter.s: Genetic_Algorithm/GaAdapter.cpp.s

.PHONY : Genetic_Algorithm/GaAdapter.s

# target to generate assembly for a file
Genetic_Algorithm/GaAdapter.cpp.s:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/Genetic_Algorithm/GaAdapter.cpp.s
.PHONY : Genetic_Algorithm/GaAdapter.cpp.s

Genetic_Algorithm/Individual.o: Genetic_Algorithm/Individual.cpp.o

.PHONY : Genetic_Algorithm/Individual.o

# target to build an object file
Genetic_Algorithm/Individual.cpp.o:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/Genetic_Algorithm/Individual.cpp.o
.PHONY : Genetic_Algorithm/Individual.cpp.o

Genetic_Algorithm/Individual.i: Genetic_Algorithm/Individual.cpp.i

.PHONY : Genetic_Algorithm/Individual.i

# target to preprocess a source file
Genetic_Algorithm/Individual.cpp.i:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/Genetic_Algorithm/Individual.cpp.i
.PHONY : Genetic_Algorithm/Individual.cpp.i

Genetic_Algorithm/Individual.s: Genetic_Algorithm/Individual.cpp.s

.PHONY : Genetic_Algorithm/Individual.s

# target to generate assembly for a file
Genetic_Algorithm/Individual.cpp.s:
	$(MAKE) -f CMakeFiles/DriverGeneticAlgorithm.dir/build.make CMakeFiles/DriverGeneticAlgorithm.dir/Genetic_Algorithm/Individual.cpp.s
.PHONY : Genetic_Algorithm/Individual.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... DriverGeneticAlgorithm"
	@echo "... edit_cache"
	@echo "... Genetic_Algorithm/Chromosome.o"
	@echo "... Genetic_Algorithm/Chromosome.i"
	@echo "... Genetic_Algorithm/Chromosome.s"
	@echo "... Genetic_Algorithm/DriverGeneticAlgorithm.o"
	@echo "... Genetic_Algorithm/DriverGeneticAlgorithm.i"
	@echo "... Genetic_Algorithm/DriverGeneticAlgorithm.s"
	@echo "... Genetic_Algorithm/GaAdapter.o"
	@echo "... Genetic_Algorithm/GaAdapter.i"
	@echo "... Genetic_Algorithm/GaAdapter.s"
	@echo "... Genetic_Algorithm/Individual.o"
	@echo "... Genetic_Algorithm/Individual.i"
	@echo "... Genetic_Algorithm/Individual.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

